### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by leifg** [fintech-to-ynab/fintech-to-ynab#101]
Is there a way to configure multiple accounts to be pushed to ynab without deploying the app twice?

In my concrete scenario I have (up to) 3 accounts because I recently signed up for the Joint Account provided my Monzo (1 Joint Account, 2 individual accounts).

**Comment by scottrobertson** [comment]
Hey

So there is no way to do it with webhooks at the moment. You can do it with the import cli just fine though. 

I will have a look and see how we can do it. The difficulty is the configuration, as we don't have any config files other than environment variables.

**Comment by ganey** [comment]
I just have 3 deployments all linked to my fork of the GitHub repository as there's no cost involved with heroku

**Comment by scottrobertson** [comment]
Yeah that works nicely, but that is pretty crappy from a UX perspective. 2 people with a join account would be 4 deployments.

**Comment by ganey** [comment]
I share YNAB with my partner so it only takes 1 deployment for the joint account

**Comment by scottrobertson** [comment]
Ok, I have got a super simple way to allow this. Will implement it as soon
as I get home :)

**Comment by scottrobertson** [comment]
Ok pushed. You can supply `?ynab_account_id` in the webhook URL now.

**Comment by scottrobertson** [comment]
@ganey this should allow you to drop down to 1 deployment 👍

**Comment by ganey** [comment]
Awesome thanks!
