### ISSUE TITLE
AMEX CSV/QIF sample exports

### ISSUE THREAD

**Issue by kot-behemoth** [fintech-to-ynab/fintech-to-ynab#105]
I finally got round to getting sample exports for Amex, as promised [here](https://github.com/fintech-to-ynab/fintech-to-ynab/issues/73#issuecomment-413811715).

Both CSV and QFX are for the same transactions. Hope this is helpful!

[amex.zip](https://github.com/fintech-to-ynab/fintech-to-ynab/files/2311731/amex.zip)

**Comment by scottrobertson** [comment]
Thank you. Is that CSV correct, no headers?

**Comment by kot-behemoth** [comment]
Yup, sadly that's it. It's straight from the export. I never use it for imports — always go with QFX myself.
