### ISSUE TITLE
Intermittent transaction import from Monzo

### ISSUE THREAD

**Issue by jkqu** [fintech-to-ynab/fintech-to-ynab#108]
Hi Scott, 

I'm getting very intermittent transaction importing into YNAB from Monzo. 

I thought it might have been due to the fact I originally set up the Heroku 6-9 months ago and there might have been some updates which didn't get pushed out automatically. However last week i restarted from fresh and whilst it seemed to work perfectly for a few days it's back to being intermittent. 

Does the Monzo app itself have to be open on the phone (in ram) to push transactions to ynab or is it all done server side?

**Comment by scottrobertson** [comment]
It's all done server side, so there is no need to open the app etc.

I recommend running the CLI tool to fill in any gaps for now until we get to the bottom of this https://github.com/fintech-to-ynab/fintech-to-ynab/wiki/Import:-Monzo#import

**Comment by jkqu** [comment]
Is this something you're aware of already then?

Let me know if you need any more detail from me to help out,

**Comment by scottrobertson** [comment]
It's not something I am aware of, no sadly. 

I will try and get some more details from you once I have time to debug.

**Comment by scottrobertson** [comment]
Unable to replicate this. Closing unless we can get some heroku logs of this happening.
