### ISSUE TITLE
URL format for Multiple Accounts

### ISSUE THREAD

**Issue by robertmarks** [fintech-to-ynab/fintech-to-ynab#126]
Trying to setup both my personal and joint Monzo to go through fintech to ynab but unsure of the way the URL should be formatted:

> You can either set the YNAB_MONZO_ACCOUNT_ID environment variable to your YNAB Account ID, or you can pass the ynab_account_id parameter into the webhook URL below.

Using a secret on the URL I had this previously for just my personal account but I'm not sure how to att the `ynab_account_id` to this URL:
`https://my-fintech-ynab-app.herokuapps.com/monzo?secret=supersecrethere`

Would be ace if you can point me in the right direction! Thanks.

**Comment by scottrobertson** [comment]
`https://my-fintech-ynab-app.herokuapps.com/monzo?secret=supersecrethere&ynab_account_id=blah`

**Comment by scottrobertson** [comment]
If you are struggling, email me (scottymeuk at gmail) and i have an easier option for you :)
