### ISSUE TITLE
Transactions coming through twice

### ISSUE THREAD

**Issue by n0k5** [fintech-to-ynab/fintech-to-ynab#128]
I've been using fintech-to-ynab since April and haven't had any problems. Suddenly though (over the last week or so) items have been pulling through twice.

I use Monzo and Heroku to run the script.

Is there a way I can troubleshoot this?

**Comment by n0k5** [comment]
Yeah I believe so; not super familiar with how this works.

**Comment by ajonesw** [comment]
Hi, what would be the best way to debug this issue I too have the same problem happening with every transaction duplicated on import for roughly the past 4-6 weeks.  Prior to this, the import worked flawlessly without any issue. I have the app running on Heroku via webhooks

**Comment by scottrobertson** [comment]
@ajonesw other than Monzo having 2 different transaction ids, i really don't see how it can happen. It has never happened to me, even when trying my hardest to replicate ite, so it's basically impossible for me to debug.

**Comment by ajonesw** [comment]
Hey Scott, the account this is happening is a Monzo Joint account (obviously with two users). Could this possibly mean there are two ids created per transaction in order for each user to receive the notification?

**Comment by omgmalm** [comment]
I'm also having the same issue on a regular account. [More people](https://community.monzo.com/t/automatically-import-transactions-to-ynab/38594/17?u=timeconsumer) seem to have the same problem

**Comment by scottrobertson** [comment]
If possible, do some debugging and get some logs etc. Impossible for me to debut as I cannot replicate it.

**Comment by scottrobertson** [comment]
The only way transactions will appear twice is if they have different transaction IDs. In that cases it's a Monzo issue.

**Comment by ajonesw** [comment]
@scottrobertson Hi Scott, further information to add to this issue. The transactions are duplicated right away but a the second transaction appears in YNAB the following day. Could it be that monzo are calling the service twice, once when pending, then again when the transaction clears. Possibly even with a different transactionID when it clears

**Comment by scottrobertson** [comment]
Even if they call it twice, if the id is the same it makes no difference. Ynab will only allow 1 transaction with the same id. 

I will reach out to Monzo and see what happens. Can you try and capture IDs of the transactions that are being duplicated so they can debug?

**Comment by ajonesw** [comment]
@scottrobertson I captured a couple some examples of this happening. Two updates are received roughly 12 hours apart for the same transaction; again presuming this delay is when the transaction clears/settles. The JSON data is identical apart from the following differences..

First Message : 
        "settled": "",
        "updated": "2019-01-03T19:55:41.087Z",

Second Message (Received following day) : 
        "settled": "2019-01-04T08:00:50.912Z",
        "updated": "2019-01-04T08:00:51.041Z",

All other data is identical including the transaction IDs.
Any way for me to share the JSON data with you without posting publicly?

**Comment by scottrobertson** [comment]
@ajonesw can you put it in a Gist and email me at scottymeuk (at) gmail.com

**Comment by scottrobertson** [comment]
To anyone experiencing this, please make sure your app is up to date. Updating on heroku is annoying, but here are some ideas: https://github.com/fintech-to-ynab/fintech-to-ynab/wiki/Getting-Started#updates-on-heroku

Closing for now. If someone can show this happening on the latest versions, then i will reopen, but i am unable to replicate this at all on the latest versions.

**Comment by QuaCKeReD** [comment]
Hi
Just setup Heroku app for webhook feed from Monzo to YNAB. 

Am getting duplicate transactions - once from webhook and another from YNAB direct import.

**Comment by scottrobertson** [comment]
@QuaCKeReD that is expected, they cannot work together in that way.
