### ISSUE TITLE
fintech to ynab

### ISSUE THREAD

**Issue by Venkatakompella** [fintech-to-ynab/fintech-to-ynab#135]
Hello There,

I have tried deploying fintech to ynab to herokuapp. However the feeds doesn't seem to come back.

Any Help would be appreciated?

**Comment by scottrobertson** [comment]
Can you explain in a bit more detail what the issue is?

**Comment by Venkatakompella** [comment]
Hey Scott,

I have followed the wiki/getting started to host or deploy the app to herokuapp. I have also registered webhook at developer.monzo.com.

I'm not receiving the transactions feed from monzo into my ynab.
How do I make this work?

BR,
Ven

**Comment by scottrobertson** [comment]
Did you previously have a prepaid monzo account?

**Comment by Venkatakompella** [comment]
I had a prepaid account.But the account that i'm seeding now is a joint account

**Comment by scottrobertson** [comment]
Can you ensure that you are using the correct account id when creating the webhook in monzo. It defaults to the prepaid account.

**Comment by Venkatakompella** [comment]
Yes,I'm using the correctid.Is there any logging that I can look into to figure out the issue?

**Comment by scottrobertson** [comment]
You can just tail the heroku logs. It will show once you perform a transaction if it's hitting the correct webhook.

**Comment by Venkatakompella** [comment]
2018-12-25T11:15:50.408341+00:00 heroku[router]: at=info method=POST path="/Monzo" host=ynabsync.herokuapp.com request_id=1f7c192e-ea61-4678-8079-dadc4f921618 fwd="52.209.175.250" dyno=web.1 connect=0ms service=3ms status=404 bytes=177 protocol=https

404 error

**Comment by scottrobertson** [comment]
Lowercase m for monzo

**Comment by Venkatakompella** [comment]
Suspected so.Thanks. I will come back if any further issues
