### ISSUE TITLE
Document YNAB_ACCOUNT_ID

### ISSUE THREAD

**Issue by Wilfred** [fintech-to-ynab/fintech-to-ynab#138]
It's really handy to specify which YNAB account you're using for Monzo. Looking at the code, it's `YNAB_ACCOUNT_ID` or `YNAB_MONZO_ACCOUNT_ID` (both work).

This environment variable isn't mentioned with the others: https://github.com/fintech-to-ynab/fintech-to-ynab/wiki/Getting-Started#environment-variables and I don't seem to be able to edit the wiki page.

This would help with #71 and possibly #101.

**Comment by scottrobertson** [comment]
Hey

It's not documented by design. It's only in the code to support backwards compatibility for people who used it before we switched to YNAB_MONZO_ACCOUNT_ID.
