### ISSUE TITLE
import accounts does not work

### ISSUE THREAD

**Issue by drphilth** [fintech-to-ynab/fintech-to-ynab#154]
Hi,

I've deployed to heroku as per instructions. Can't seem to get the list of accounts to work. Output is:

$heroku run -a my-herokuapp bin/import accounts
Running bin/import accounts on ⬢ my-herokuapp... up, run.4195 (Free)
error: wrong number of arguments (given 1, expected 3). Use --trace to view backtrace

$heroku run -a my-herokuapp bin/import accounts --trace
Running bin/import accounts --trace on ⬢ my-herokuapp... up, run.2962 (Free)
Traceback (most recent call last):
        8: from /app/vendor/bundle/ruby/2.5.0/gems/commander-4.4.7/lib/commander/import.rb:5:in `block in <top (required)>'
        7: from /app/vendor/bundle/ruby/2.5.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
        6: from /app/vendor/bundle/ruby/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:68:in `run!'
        5: from /app/vendor/bundle/ruby/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:446:in `run_active_command'
        4: from /app/vendor/bundle/ruby/2.5.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
        3: from /app/vendor/bundle/ruby/2.5.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
        2: from bin/import:16:in `block (2 levels) in <main>'
        1: from bin/import:16:in `new'
/app/vendor/bundle/ruby/2.5.0/bundler/gems/f2ynab-8294b77c3e9a/lib/f2ynab/ynab/client.rb:4:in `initialize': wrong number of arguments (given 1, expected 3) (ArgumentError)

Any idea where this is going wrong. Falling at the first hurdle like this makes me think I've done something wrong

**Comment by drphilth** [comment]
Also can't import from teller - get the following error. Not sure if it is related or if it is something separate

`>heroku run -a my-herokuapp bin/import teller --token MYTOKEN --ynab_account_id MY_ID
Running bin/import teller --token MYTOKEN --ynab_account_id MY_ID on ⬢ my-herokuapp... up, run.8692 (Free)
error: uninitialized constant Import. Use --trace to view backtrace

>heroku run -a my-herokuapp bin/import teller --token MYTOKEN --ynab_account_id MY_ID --trace
Running bin/import teller --token MYTOKEN --ynab_account_id MY_ID --trace on ⬢ my-herokuapp... up, run.6638 (Free)
Traceback (most recent call last):
        6: from /app/vendor/bundle/ruby/2.5.0/gems/commander-4.4.7/lib/commander/import.rb:5:in `block in <top (required)>'
        5: from /app/vendor/bundle/ruby/2.5.0/gems/commander-4.4.7/lib/commander/delegates.rb:15:in `run!'
        4: from /app/vendor/bundle/ruby/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:68:in `run!'
        3: from /app/vendor/bundle/ruby/2.5.0/gems/commander-4.4.7/lib/commander/runner.rb:446:in `run_active_command'
        2: from /app/vendor/bundle/ruby/2.5.0/gems/commander-4.4.7/lib/commander/command.rb:153:in `run'
        1: from /app/vendor/bundle/ruby/2.5.0/gems/commander-4.4.7/lib/commander/command.rb:182:in `call'
bin/import:99:in `block (2 levels) in <main>': uninitialized constant Import (NameError)`

**Comment by drphilth** [comment]
I think these may be two separate issues. I'm doing some regression testing. Commit 931bb4b022c0305bc582cfde2bb33af981106538 works as expected. The most recent commit fails as above, but specifying a full teller import command including a valid --teller_account_id works as expected.

**Comment by blckmstr** [comment]
yeah the docs arent up to date and theres definitely bugs in this whole thing.

Did you set up the teller accounts and connect your bank to teller? It seems teller doesnt offer connections to any UK banks, seems all US banks. Also theres an issue which states that teller is closing down anyway

**Comment by scottrobertson** [comment]
@blckmstr teller shut down since this was built. They may have relaunched since, but I have not looked to be honest. They should be removed from this.

**Comment by drphilth** [comment]
@scottrobertson @blckmstr Yes, this was logged when teller was still active. Shame we've lost the ability to import from lots of UK accounts, I had actually got it ruining with some nice periodic cron jobs running.

I'm going to close the issue because it isn't relevant anymore
