### ISSUE TITLE
Todo: Remove Teller

### ISSUE THREAD

**Issue by scottrobertson** [fintech-to-ynab/fintech-to-ynab#159]
Teller is shutting down the API, so we need to remove it and any banks that come with it.

**Comment by blckmstr** [comment]
what does this mean for all the banks associated with it? will this leave only monzo and starling working in this repo?

**Comment by scottrobertson** [comment]
@blckmstr that is correct yeah.

**Comment by blckmstr** [comment]
Interesting, I have looked around a little bit and it seems very painful to integrate any brick and mortar UK banks. I would be happy to collaborate to get some new integrations in place. Let me know if you have any avenues, or if you want to continue with this project in general

Thanks

**Comment by scottrobertson** [comment]
@blckmstr it's not possible to use Open Banking for this project due to a number of reasons. Mainly regulations, and the lack of storage to store access tokens etc. 

I launched syncforynab about a year ago to solve these issues.

**Comment by blckmstr** [comment]
OK, so from your perspective you have already made it possible to import all you need from UK banks into YNAB. However, its split across multiple repos? There are two separate repos. This one for monzo and new banks like that.  Syncforynab for brick and mortar banks? If that is the case I will try and make it work and if it does maybe I can submit a pr to improve the readme a bit?

**Comment by scottrobertson** [comment]
> This project is no longer open source

Sync For YNAB has never been open source.
