### ISSUE TITLE
Hooks on import / customised import

### ISSUE THREAD

**Issue by cellulosa** [fintech-to-ynab/fintech-to-ynab#186]
Hi @scottrobertson and thank you for the great tool!

I couldn't find in the wiki if it is possible to customise the import process. I'll make two specific examples of what I am trying to achieve to explain myself:

1) As I have been adding YNAB transactions manually until now, I want to import transactions starting from DATE - which I know are the "new ones";
2) I have a Monzo Joint account where all transactions should be divided by 2 before being imported into YNAB to weight correctly in my personal expenses.

Is this something `fintech-to-ynab` currently enables users to do? If not, are these being considered in future release? Or how could I help to add these functionalities (as in, where in the code)?

Many thanks

**Comment by scottrobertson** [comment]
Hey

You can run `bin/import monzo --help` to see the params :)

Or you can see them here: https://github.com/fintech-to-ynab/fintech-to-ynab/blob/master/bin/import#L27-L30
