### ISSUE TITLE
Waiting for Personal Starling Webhooks

### ISSUE THREAD

**Issue by scottrobertson** [fintech-to-ynab/fintech-to-ynab#23]
To allow Starling to work easily, we need them to support Personal Webhooks. Righy now we need to create clients and I don't see them being approved very quickly/at all, which makes this project super difficult to use. It will apparently be worked on soon 👍 

https://trello.com/c/rviKbwNQ/47-personal-access-webhooks

**Comment by Stephan5** [comment]
They are coming very soon, promise 👍

**Comment by scottrobertson** [comment]
I think we may need to just remove Starling from the README for now until this is done. I suspect it will be a while as they have a lot of their plates.

**Comment by philtate** [comment]
It looks like Starling now has webhooks.

**Comment by scottrobertson** [comment]
@philtate they have webhooks, but only via oAuth, which you need to submit for approval etc. Sadly that makes them unusable. We are still waiting on personal webhooks (similar to access tokens vs client/secret key)

**Comment by philtate** [comment]
Doh! That's a shame. It's the integration I'm looking for as I miss a Starling import to YNAB.

**Comment by scottrobertson** [comment]
@philtate for now, https://github.com/scottrobertson/starling-export works well :)

**Comment by philtate** [comment]
Thanks! I'll give it a go with my very near negative Ruby skills!

**Comment by allistera** [comment]
Does this project support Starling yet? I came here from their developer-resources project and managed to get Monzo integration working perfectly although judging from the Wiki it isn't compatible with Starling. If not should the `readme.md` not be updated to clear this up? 

Thanks!

**Comment by scottrobertson** [comment]
@allistera not yet. Waiting for Starling. Feel free to PR a readme change if you like 👍

**Comment by allistera** [comment]
Awesome thanks for the update Scott, PR here https://github.com/scottrobertson/fintech-to-ynab/pull/43

**Comment by scottrobertson** [comment]
Thanks @allistera. Merged. 

Any updates @Stephan5?

**Comment by scottrobertson** [comment]
I have pushed a Starling import script. This allows us to import Starling, but not in real-time.

https://github.com/scottrobertson/fintech-to-ynab/wiki/import:-Starling-Bank

**Comment by scottrobertson** [comment]
Gonna just close this. I have removed references to Starling webhooks for now until they add support.

**Comment by allistera** [comment]
I guess the only possible option would be to pull rather than push. Although would require a lot of rearchitecting the project for a 'supposedly' temporary solution. Agree with your decision to remove them until support is provided :)

**Comment by scottrobertson** [comment]
@allistera Pull is already implemented :) https://github.com/scottrobertson/fintech-to-ynab/wiki/import:-Starling-Bank

**Comment by adambowles** [comment]
Looks like they're here: https://developer.starlingbank.com/personal/list

**Comment by scottrobertson** [comment]
If anyone wants to take this, feel free. I wont have time this week, and I am away the week after. Just needs support adding to https://github.com/fintech-to-ynab/fintech-to-ynab/blob/master/app/controllers/starling_controller.rb similar to https://github.com/fintech-to-ynab/fintech-to-ynab/blob/master/app/controllers/monzo_controller.rb

**Comment by scottrobertson** [comment]
Added some basic support. It's missing some event types, but we can add them as we find them. Have asked Starling for a list.

Docs updated: https://github.com/fintech-to-ynab/fintech-to-ynab/wiki/import:-Starling-Bank
