### ISSUE TITLE
Use the teller.io API to get direct debits/standing orders

### ISSUE THREAD

**Issue by rossdargan** [fintech-to-ynab/fintech-to-ynab#53]
This could be used to set up and maintain scheduled payments in ynab :)

**Comment by lucasomigli** [comment]
Just tried to connect UK Barclays to Teller.io but unfortunately doesn't work. Devs from teller.io say it's a known problem and they're currently trying to work on it. 

Might be nice to bypass the problem using other third-party apps that do a similar thing to Teller.io. This way, chances of working with different institutions would increase.

**Comment by lucasomigli** [comment]
@scottrobertson I see. Then, I reckon only way is to wait for Teller’s devs to come up with a solution themselves. UK Barclays does have an API tough, maybe could be an idea to directly connect it to

**Comment by lucasomigli** [comment]
@scottrobertson I see. Then, I reckon only way is to wait for Teller’s devs to come up with a solution themselves. UK Barclays does have an API tough, maybe there’s a way to direct connect their API to fintech-to-YNAB without Teller.io?

**Comment by scottrobertson** [comment]
@lucasomigli I will take a look, but having just spent 10 minutes doing the signup process, and submitting my application for approval, i don't have high hopes that this will be easy enough for people to use. Most people using this are not software developers.

**Comment by scottrobertson** [comment]
Teller API shutting down
