### ISSUE TITLE
Declined transactions still imported

### ISSUE THREAD

**Issue by ganey** [fintech-to-ynab/fintech-to-ynab#55]
Declined transactions still fire a webhook so the Monzo transactions are still being imported

**Comment by scottrobertson** [comment]
Just to confirm, is this on v1 or v2?

**Comment by ganey** [comment]
V2 I deployed around 12 days ago

**Comment by scottrobertson** [comment]
Should be fixed now

**Comment by ganey** [comment]
Awesome thanks!
