### ISSUE TITLE
Business banking accounts

### ISSUE THREAD

**Issue by crt434** [fintech-to-ynab/fintech-to-ynab#58]
@scottrobertson really cool project :) will it work with barclays business bank accounts the import process? I'm really keen to match up. Plus how far back would the data be able to go? Could I for instance add into YNAB previous spending dating back few months?

**Comment by scottrobertson** [comment]
Hey

It works with Barclays business, yes :)

And you should be able to go back all the way to the start of your account.

**Comment by crt434** [comment]
That was quick :) Cool will close this out. And no doubt come back with more ideas for cool stuff to add, really cool project. Wish banks already did this stuff as standard
