### ISSUE TITLE
Will skipping of emoji and tags return?

### ISSUE THREAD

**Issue by adambowles** [fintech-to-ynab/fintech-to-ynab#63]
I updated to the YNAB API version this week and transactions have emoji and hashtags in the memo, where I had opted out of them in v1.

**Comment by scottrobertson** [comment]
@adambowles i removed them in v2 as i wanted to keep things simple. Feel free to submit a PR if you need them :)

**Comment by adambowles** [comment]
Roger, I'll have a look
