### ISSUE TITLE
monzo to ynab issues

### ISSUE THREAD

**Issue by wabit** [fintech-to-ynab/fintech-to-ynab#66]
I am having some issues getting this to work with my Monzo account.

when I try to run the import I am getting to following error:

`NameError: undefined local variable or method `monzo_access_token' for main:Object
`
I am very likely missing something as the instructions are not very clear.

Any help would be great

**Comment by scottrobertson** [comment]
Hey

`monzo_access_token` is a variable you need to assign.

```
monzo_access_token = 'blah'
monzo_account_id = 'blah'
ynab_account_id = 'blah'
Import::Monzo.new(monzo_access_token, monzo_account_id, ynab_account_id).import
```

**Comment by wabit** [comment]
i have it assigned along with the rest of them 
<img width="621" alt="vars" src="https://user-images.githubusercontent.com/3354647/41498498-5c98e3dc-7167-11e8-96db-43685f2de7a1.png">

**Comment by scottrobertson** [comment]
Those are environment variables for the webhook setup, not the one off import scripts. You need to assign them like above for the one off import scripts.

**Comment by wabit** [comment]
That makes more sense thanks seems to be working. I am struggling to get the webhook to work though is there a way of testing it without spending any money?
