### ISSUE TITLE
Transaction State

### ISSUE THREAD

**Issue by rndthoughts** [fintech-to-ynab/fintech-to-ynab#67]
Ive setup per instructions but i dont seem to get transactions added to ynab even though i verified the keys used and import works. Do pending transactions get sent immediately i make payment or do they have to clear?  Is there any POST json i can use to test the ynab insert works?

**Comment by scottrobertson** [comment]
Which bank are you using? Are you referring to webhooks, or historical imports?

**Comment by rndthoughts** [comment]
Sorry should have been clearer! Using starling. I can run the import command and it pushes transactions to ynab. But when i make a purchase nothing happens.

**Comment by scottrobertson** [comment]
Just to confirm, have you setup the app on Heroku/Similar, and have you added the URL to Starling's dev dashboard?

**Comment by rndthoughts** [comment]
Yes i used the Heroku install button.  On Starling, I wasn't sure which actions to check as it's not in the getting started guid on here but I have:

Direct Debit,  Interest Payment,  Faster Payment Out,  Internal Transfer, Interest Charge,  Interest Waived Deposit,  Card,  Faster Payment Reversal,  Faster Payment In,  Mobile Wallet,  Direct Credit,  Cash Withdrawal

Payload URL points to: https://nameofmyapp.herokuapp.com/starling

**Comment by rndthoughts** [comment]
I've just noticed there is a "Production Secret" option as well?

**Comment by scottrobertson** [comment]
Does going to `https://nameofmyapp.herokuapp.com/` work? What response do you get from it?

**Comment by rndthoughts** [comment]
Doing a GET gives me: {"error":"unauthorised"} (401)

**Comment by rndthoughts** [comment]
OK I think I know what it is - I am using Apply Pay which sets the webhook type in the json as "TRANSACTION_MOBILE_WALLET"

**Comment by scottrobertson** [comment]
This was caused by https://github.com/fintech-to-ynab/fintech-to-ynab/issues/65

**Comment by scottrobertson** [comment]
@rndthoughts ha yes. Just pushed a fix, and emailed you :)

**Comment by rndthoughts** [comment]
If i restart my heroku dyno will it pull the new code?

**Comment by scottrobertson** [comment]
Errr, you will need to tell it to redeploy. Let me get the steps.

**Comment by scottrobertson** [comment]
Ah, just click the app, then the deploy tab. You should be able to do it from there.

**Comment by rndthoughts** [comment]
Not sure how I try again without a new purchase?  If I resubmit the json, I’m guessing i'll need some headers set?

**Comment by scottrobertson** [comment]
Errmmm, resubmitting the JSON should be totally fine, as long as you have the correct secret set in the url.

**Comment by rndthoughts** [comment]
OK so in the deploy tab, I guess i need to connect to github to pull the code from your project.  But I'm only able to see my own projects?

**Comment by scottrobertson** [comment]
Hmm it should be connected already. Let me set one up again using the button and i will see.

**Comment by ganey** [comment]
You could just fork the project and then sync changes every once in a while. I think you can even set it so it would auto update the Heroku instance

**Comment by rndthoughts** [comment]
Yup that got it 👍.  It's now working - thanks for the help guys!

**Comment by scottrobertson** [comment]
Awesome! Will try and work out a way to make that easier and update the docs if i find a way.
