### ISSUE TITLE
Goal Transactions on Starling

### ISSUE THREAD

**Issue by rndthoughts** [fintech-to-ynab/fintech-to-ynab#69]
When i transfer money to my goals in Starling, I dont seem to get a transaction inserted into YNAB.  Is this because webhooks don't support this type of transaction?

**Comment by scottrobertson** [comment]
@rndthoughts could you get the JSON from the logs and check the "webhookType", and send it over.

**Comment by scottrobertson** [comment]
Or perhaps they don't send webhooks for those (in which case, we will need to get them to fix it).

**Comment by rndthoughts** [comment]
Yes that appears to be the issue (no webhooks).  There are no log entries for those types.  I guess because the money doesnt actually enter or exit the account.  However, as far as ynab is concerned I would assume you would want to assign them to ynab goals?

**Comment by scottrobertson** [comment]
Yeah that makes sense.

I think as far as YNAB is concerned, it wouldn't care as the money is not moving anywhere.

**Comment by rndthoughts** [comment]
It's a difficult one - your Starling balance actually changes and transactions get inserted on Starling but YNAB knows nothing about them so if you are trying to track that you assigned some cash to a particular goal in YNAB, you'd need to enter it manually.  Considering Starling goals can be recurring, it might be something worth looking at (optionally)?

**Comment by scottrobertson** [comment]
I am not sure it really makes sense to be honest. Goals in YNAB are not linked to transactions or accounts in anyway. A goal can span multiple accounts for example. Adding a transaction to YNAB would also not change a goal in anyway, as no money is being moved anywhere.

I also don't know how it would even work in YNAB, as it needs a inflow/outflow, so the money would leave the starling account YNAB, but where would it go?

**Comment by ganey** [comment]
Yeah generally they work out as more effort than it's worth. The YNAB mobile app has a bug with auto tagging transfers correctly, so you have to edit each transaction anyway.

I only added a pot to actually ring fence the money from my main account, but like you said, they are all the same pot as far as YNAB.
