### ISSUE TITLE
How do I let the app know if i have a monzo account in YNAB?

### ISSUE THREAD

**Issue by feleio** [fintech-to-ynab/fintech-to-ynab#71]
I already have an account which i manually enter my transaction from monzo. How do I tell the ap about the existing monzo account in YNAB?

**Comment by feleio** [comment]
Ah I found that there is a account id env var. sorry for the stupid question.

**Comment by feleio** [comment]
I assume YNAB_ACCOUNT_ID means the account id of Monzo, is it correct? Thanks

**Comment by rndthoughts** [comment]
No that’s your YNAB account id. You set it to tell the app which account to push your monzo transactions into.

**Comment by feleio** [comment]
Just finish setting up and it works now. Thanks

**Comment by scottrobertson** [comment]
Awesome :)

The variable name should really be `MONZO_YNAB_ACCOUNT_ID` or something, but to change it requires a lot of people to change their configs. I will try and sort that out in a bit better way soon.
