### ISSUE TITLE
Duplicated transaction in YNAB starling account

### ISSUE THREAD

**Issue by feleio** [fintech-to-ynab/fintech-to-ynab#72]
I have tried to send £1 from monzo to starling account . The transactions appear in YNAB which is really nice but there always be 2 same duplicated transactions in my starling account. I have checked all Webhook Types when i create a webhook in starling developer setting. Can it be the reason? 

P.S. I found the duplicated transaction wont come together at the same time. second one always come few minutes after the first one

**Comment by feleio** [comment]
From the log, I was there is 2 POST call to heroku app. they are separated by 2 minutes. the payload of two calls seems identical.

**Comment by feleio** [comment]
I confirmed that there is only one webhook created

**Comment by feleio** [comment]
Thanks Ganey. I am getting 2 POST to the same path /starling. but Not sure if they are both from starling. 
What do you mean by 
```
Monzo Webhook being auto set as a transfer by YNAB
```
I have also setup the monzo webhook for my YNAB Monzo account. I suppose that one works well as i saw a POST to path /monzo.

I also tested that when someone transfer fund to my starling account . I have the same duplicated transction issue . 

Thanks :)

**Comment by ganey** [comment]
Sometimes YNAB figures out the transfer and will set it up on the other account in YNAB, doesn't seem to be the case here. 

Sounds like the issue is definitely with the starling webhook though. I'm not sure what a webhook payload looks like, or if all of them have a similar date field, if they do we could maybe try using the transaction date time as the import_id to stop YNAB inserting duplicates?

**Comment by rndthoughts** [comment]
I'm getting the same issue.  I notice that the first request has "Client Request Interrupted" on it so may Starling are retrying as they dont get a 200 from Heroku?

https://devcenter.heroku.com/changelog-items/662

**Comment by ganey** [comment]
It might be that Starling aren't waiting long enough for a response so retrying the webhook? 

Does it still trigger twice if two transactions are made close together? 
Free dynos on Heroku go to sleep so may not spin up fast enough for the first webhook, it used to be around 30 minutes of inactivity to trigger the sleep state.

**Comment by scottrobertson** [comment]
I have not had a chance to dig into this yet, but it's worth noting that it's very unlikely the import_id would catch this. Basically, it has to handle the case in which we get multiple transactions of the same value in 1 day, so it cannot count them as duplicate.

**Comment by scottrobertson** [comment]
From the logs, i cannot see why the interrupted error is coming up. Requests are all completing very quickly.

**Comment by scottrobertson** [comment]
@rndthoughts is your issue with all transactions, or just faster payments?

**Comment by rndthoughts** [comment]
@scottrobertson I've only used Apple Pay or my Starling card for my transactions - I'm currently mid bank account switch to Starling so I haven't made any other types of transaction.

**Comment by ganey** [comment]
I asked on Starling's Slack for the timeouts and got the following response:

> we have a 2 second timeout for opening the socket
once we have finished sending data over that socket we wait a further 2 seconds for a response

**Comment by scottrobertson** [comment]
Ok, then that seems like it's the issue. The app can take longer than 2 seconds to boot.

**Comment by thomaspurchas** [comment]
I have just created a PR that should deal with this:
https://github.com/fintech-to-ynab/fintech-to-ynab/pull/74

It does need review because I'm not a ruby developer, and this stuff confuses me a little.

**Comment by rndthoughts** [comment]
> Ok, i think the best way to confirm this is to make one, when it's sleeping and see if it does it.

Just did two transactions within 30 mins of each other.  The first one duplicated (it was the first transaction I've made today), the second didn't.  So it's got to be an idle timeout.

**Comment by scottrobertson** [comment]
Awesome, thank you for confirming. Will have a think of how to deal with this.
