### ISSUE TITLE
Use "Nordic API Gateway" to support nordic banks

### ISSUE THREAD

**Issue by duch11** [fintech-to-ynab/fintech-to-ynab#91]
As I wrote in #73 Bank Requests, I'll be trying to add support for Nordic API Gateway. It's made by Spiir, which is a great app in itself, but I want YNAB! 
And I want it to support automatic transactions from Scandinavia! 

My Idea is that with this PS2D "Nordic API Gateway", we'll be able to automatically import the transactions from a bank account, into a YNAB account. The API handles user authentication in a separate login window, and then grants access to the transactions.
Link: https://developer.nordicapigateway.com/ 

In the coming days, I'll be looking into how the API works, and how this Projects innards are working, I'll be posting my progress and conclusions here.

**Comment by scottrobertson** [comment]
Awesome 👍 let me know how your research pans out.

**Comment by duch11** [comment]
My conclusions so far:
I'm still lacking understanding of how this project actually works, it's my first time with ruby. 
How is the program flow? 
Where is the main method?
Where would I write code, to support a new API?

In regards to the API, it seems pretty straight forward, but I'm puzzled by what the "Redirect URL" would be?
![API Getting started](https://user-images.githubusercontent.com/17031368/43579777-7e9bda78-9653-11e8-97ae-8c6df62d572a.png)

**Comment by scottrobertson** [comment]
Ah, it requires oAuth. I am not sure that is going to work then. We do not have anywhere to store the access tokens etc (we have no databases - and i am 100% against introducing one).

**Comment by scottrobertson** [comment]
As for where you would write them, take a look at the others in https://github.com/fintech-to-ynab/fintech-to-ynab/tree/master/app/services/import

**Comment by duch11** [comment]
Thank you. 
In regards to oAuth, would it be acceptable to store it in a local file, if the program were to run locally on ones own machine?
Would there be a workaround?

**Comment by scottrobertson** [comment]
The problem is that most people run it via Heroku, and as soon as they do a deploy, it's all lost. That will result in a lot of confusion. 

Right now, i think the best option is to just build the importer with the ability to pass in the token, like we do with Monzo. Keep all of the oAuth logic outside of the app until we can think of a solution for it.

**Comment by scottrobertson** [comment]
For me personally, i have a seperate little service that stores/refreshes Monzo tokens. I then assign that to an ENV var via a bash script. And then i pass that into the Fintech to YNAB importer.

**Comment by duch11** [comment]
Thank you for your help :) 👍 
I'll be making some sort of solution for this, but maybe not on this project then.
But totally understandable, confusion is a bad thing, it would be better to have a separate project for services that require oAuth :) 
I'll try to look for that instead then :)

**Comment by mattsson** [comment]
Hi @duch11, did you get further with this?

**Comment by duch11** [comment]
No unfortunately not :) 

Med venlig hilsen / Best Regards
 Jonas Ladefoged Holm
 jonas@holm.tech

**Comment by mattsson** [comment]
Ok. In the meantime I’ve created a small node.js script that exports my bank transactions using Nordic API Gateway and imports them into YNAB directly using the public YNAB API.

**Comment by duch11** [comment]
Perfect! 
I have been working on an angular frontend for managing account sync. Wondering if we could merge?

Med venlig hilsen / Best Regards
 Jonas Ladefoged Holm
 jonas@holm.tech

**Comment by mattsson** [comment]
The script is not very generic, very much built for my purposes but I do want to make it available in a more widely usable format. I'll post in here when I do. :)

**Comment by scottrobertson** [comment]
It's using oAuth, so we cannot really add it here as we don't have a database in this application to store the access tokens etc.

However, if someone wants to reach out to me at scottymeuk (at) gmail.com, i can look at adding it to syncforynab.com
