### ISSUE TITLE
Last part of getting started, pls help!

### ISSUE THREAD

**Issue by remington82** [fintech-to-ynab/fintech-to-ynab#97]
Hi Scott, thanks for putting this together... I'm trying to follow the webhooks instructions for Monzo

I got to the final furlong with this, but then got confused by the last part of the getting started guide, 'Connect to bank' (for Monzo). Here's what I put into the request body... 
{
	"account_id": "[from YNAB MONZO ID - as described, the final part of the URL]",
	"url": "[APP URL?secret=SECRETSTRING, as instructed a random string]"
}

but then I'm not sure what to do after that. Do I need to save it? Does clicking 'SEND button save this? In any event, when I click 'SEND' I get the following error:

Sorry if completely asinine question - first time heroku user, but desperate to get this working to make YNAB easier! Thanks

**Comment by remington82** [comment]
Here's the error I get in the response body: 

code:"forbidden.insufficient_permissions"
message:"Access forbidden due to insufficient permissions"

**Comment by scottrobertson** [comment]
Can you just confirm where you are trying to send that data? In Monzo's dev portal?

The account_id in there is not your YNAB account id, it's your Monzo account ID, which you get by calling the "List Accounts" endpoint on that page.

**Comment by scottrobertson** [comment]
Let me know if that does not work.

**Comment by scottrobertson** [comment]
I have updated the wiki to make this a bit more clear

**Comment by remington82** [comment]
Thanks Scott. I got it working using this tutorial. Thanks for updating
though

https://community.monzo.com/t/automatically-import-transactions-to-ynab/38594/6
